---
title: "OECD_clustering"
output: html_document
date: "2024-04-12"
---

## Import libraries and dataset

```{r}
library(tidyverse)
library(insight)
library(stargazer)
library(dendextend)
library(ggplot2)
library(gridExtra)

mortality <- read.csv("oecd_mortality_diseases.csv")
mortality <- data.frame(country = mortality$REF_AREA, death_cause = mortality$DEATH_CAUSE, val = mortality$OBS_VALUE)

index <- order(mortality$country, mortality$death_cause)
ordered <- mortality[index,]

causes <- c("CIRC", "DIGE", "ENDO", "INFE", "NEOP", "NERV", "RESP", "BLOOD", "MENT")
countries <- unique(ordered$country)
mortality_matrix <- matrix(c(ordered[,3]), nrow = length(countries), byrow = TRUE, 
                    dimnames = list(countries,causes))
mortality_scaled <- scale(mortality_matrix)
```

## Present summary statistics

```{r}
# max mortality rates in each country and for each disease

mortality_causes <- max.col(t(mortality_matrix))
max_country <- data.frame(Country = countries[mortality_causes], 
                          Rate = apply(mortality_matrix, 2, max, na.rm=TRUE))

# export tables
stargazer(max_country, summary = FALSE, type = "text")

# export table of descriptive statistics
summ <- stargazer(mortality_matrix, summary = TRUE, median = TRUE, type = "text")

```

```{r}
# scatter plot
pairs(mortality_matrix, upper.panel = NULL, cex = 0.8, gap = 0)

```


```{r}
# clustering 
method <- "complete"
dist <- dist(mortality_scaled, method = "euclidean")
cluster <- hclust(dist, method = method)
dend <- as.dendrogram(cluster)

# form clusters and plot dendrogram
h = 6.6
dend <- color_labels(dend, h = h,
                     col = c("red","lightgreen", "purple", "cornflowerblue"))
dend <- color_branches(dend, h = h,
                       col = c("red","lightgreen", "purple", "cornflowerblue"))
plot(dend, xlab = "",
     ylab = "Tree height (Euclidean distance)",
     sub = NA, hang = -1)

# scatter plot with clusters
clusters <- cutree(dend, h = h)
pairs(mortality_matrix, upper.panel = NULL, cex = 1, pch = 16, gap = 0, 
      col = c("cornflowerblue" ,"lightgreen", "purple", "red")[clusters])


```

## Boxplot of clusters

```{r}

# add cluster information to data
mortality_clusters <- as.data.frame(mortality_matrix)
mortality_clusters$cluster <- clusters

# boxplots of clusters
par(mfrow = c(3,3))

circ <- ggplot(mortality_clusters, aes(x=cluster, y=CIRC, fill=c("cluster 1", "cluster 2", "cluster 3", "cluster 4")[cluster])) + 
    geom_boxplot(alpha=0.9) +
    scale_fill_manual(values=c("cornflowerblue" ,"lightgreen", "purple", "red")) +
    theme(legend.position="none")

dige <- ggplot(mortality_clusters, aes(x=cluster, y=DIGE, fill=c("cluster 1", "cluster 2", "cluster 3", "cluster 4")[cluster])) + 
  geom_boxplot(alpha=0.9) +
  scale_fill_manual(values=c("cornflowerblue" ,"lightgreen", "purple", "red")) +
  theme(legend.position="none")

endo <- ggplot(mortality_clusters, aes(x=cluster, y=ENDO, fill=c("cluster 1", "cluster 2", "cluster 3", "cluster 4")[cluster])) + 
  geom_boxplot(alpha=0.9) +
  scale_fill_manual(values=c("cornflowerblue" ,"lightgreen", "purple", "red")) +
  theme(legend.position="none")

infe <- ggplot(mortality_clusters, aes(x=cluster, y=INFE, fill=c("cluster 1", "cluster 2", "cluster 3", "cluster 4")[cluster])) + 
  geom_boxplot(alpha=0.9) +
  scale_fill_manual(values=c("cornflowerblue" ,"lightgreen", "purple", "red")) +
  theme(legend.position="none")

neop <- ggplot(mortality_clusters, aes(x=cluster, y=NEOP, fill=c("cluster 1", "cluster 2", "cluster 3", "cluster 4")[cluster])) + 
  geom_boxplot(alpha=0.9) +
  scale_fill_manual(values=c("cornflowerblue" ,"lightgreen", "purple", "red")) +
  theme(legend.position="none")

nerv <- ggplot(mortality_clusters, aes(x=cluster, y=NERV, fill=c("cluster 1", "cluster 2", "cluster 3", "cluster 4")[cluster])) + 
  geom_boxplot(alpha=0.9) +
  scale_fill_manual(values=c("cornflowerblue" ,"lightgreen", "purple", "red")) +
  theme(legend.position="none")

resp <- ggplot(mortality_clusters, aes(x=cluster, y=RESP, fill=c("cluster 1", "cluster 2", "cluster 3", "cluster 4")[cluster])) + 
  geom_boxplot(alpha=0.9) +
  scale_fill_manual(values=c("cornflowerblue" ,"lightgreen", "purple", "red")) +
  theme(legend.position="none")

blood <- ggplot(mortality_clusters, aes(x=cluster, y=BLOOD, fill=c("cluster 1", "cluster 2", "cluster 3", "cluster 4")[cluster])) + 
  geom_boxplot(alpha=0.9) +
  scale_fill_manual(values=c("cornflowerblue" ,"lightgreen", "purple", "red")) +
  theme(legend.position="none")

ment <- ggplot(mortality_clusters, aes(x=cluster, y=MENT, fill=c("cluster 1", "cluster 2", "cluster 3", "cluster 4")[cluster])) + 
  geom_boxplot(alpha=0.9) +
  scale_fill_manual(values=c("cornflowerblue" ,"lightgreen", "purple", "red")) +
  theme(legend.position="none")

grid.arrange(circ,dige,endo,neop,infe,nerv,resp,blood,ment,nrow = 3)

```
